Python2 is deprecated for a while
RPi-Distro/rpi-source pull request #10
Opened 2022-06-28 09:41 UTC by surak

This makes rpi-source compatible with python3.

2022-06-28 10:08 UTC, surak commented
This integrates #2 on a single pull request

2022-07-11 01:10 UTC, fake-name commented
At least [d60fc65](https://github.com/RPi-Distro/rpi-source/pull/10/commits/d60fc65ec49b2071da849fe17d0a378a3c442278) is broken. You're writing to a file opened in text mode with bytes. Either open it with mode `wb`, and encode the bytes before writing, or just drop the encode.

2022-07-11 01:16 UTC, fake-name commented
This is at least partially broken:

```
durr@raspberrypi:~/seeed-linux-dtoverlays $ /usr/local/bin/rpi-source -q --tag-update
Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 367, in <module>
    update_tag()
  File "/usr/local/bin/rpi-source", line 170, in update_tag
    writef(update_tag_file, ref)
  File "/usr/local/bin/rpi-source", line 112, in writef
    f.write(str.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

```

It appears that `writef()` is called with both strings and bytes.

2022-08-02 15:52 UTC, DrBu7cher requested changes
Please change line 170 to
```python
    writef(update_tag_file, ref.encode("utf-8"))
```

2022-08-02 15:52 UTC, DrBu7cher commented on rpi-source
> +import urllib.parse
```suggestion
import urllib.request, urllib.parse, urllib.error
```
This should do the same, right?

2022-08-02 17:49 UTC, surak commented
> Please change line 170 to
> 
> ```python
>     writef(update_tag_file, ref.encode("utf-8"))
> ```

done!

2022-08-04 14:19 UTC, MedericFourmy commented
I experienced this error:

```
 *** SoC: BCM2711

 *** Arch: 64-bit

 *** Using: /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz
Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 383, in <module>
    kernel = debian_method(debianlog)
  File "/usr/local/bin/rpi-source", line 278, in debian_method
    fw_rev = re.search(r'firmware as of ([0-9a-fA-F]+)', debian_changelog)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

The error disappears when changing line 275 to:

`        debian_changelog = f.read().decode('utf-8')`

2022-08-04 14:34 UTC, MedericFourmy commented
But then I encounter this error:

```
 *** SoC: BCM2711

 *** Arch: 64-bit

 *** Using: /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz

 *** Latest firmware revision: 61966732d03de9b71baf561f920e018b54c241ac

 *** Linux source commit: b'6f921e98008589258f97243fb6658d09750f0a2f'

 *** Download kernel source
--2022-08-04 16:21:51--  https://github.com/raspberrypi/linux/archive/b6f921e98008589258f97243fb6658d09750f0a2f.tar.gz
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/raspberrypi/linux/tar.gz/b6f921e98008589258f97243fb6658d09750f0a2f [following]
--2022-08-04 16:21:51--  https://codeload.github.com/raspberrypi/linux/tar.gz/b6f921e98008589258f97243fb6658d09750f0a2f
Resolving codeload.github.com (codeload.github.com)... 140.82.121.9
Connecting to codeload.github.com (codeload.github.com)|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-08-04 16:21:52 ERROR 404: Not Found.

Traceback (most recent call last):
  File "/usr/local/bin/rpi-source", line 400, in <module>
    sh("wget %s -O %s https://github.com/raspberrypi/linux/archive/%s.tar.gz" % (("-q" if args.quiet else ""), linux_tar, kernel.git_hash))
  File "/usr/local/bin/rpi-source", line 96, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'wget  -O /home/gepetto/arducam/virtual_video_node/linux-b'6f921e98008589258f97243fb6658d09750f0a2f'.tar.gz https://github.com/raspberrypi/linux/archive/b'6f921e98008589258f97243fb6658d09750f0a2f'.tar.gz' returned non-zero exit status 8
```

Not sure what to do after that. I finally resorted to using the python2 script.

2022-08-04 17:14 UTC, surak commented
> I experienced this error:
> 
> ```
>  *** SoC: BCM2711
> 
>  *** Arch: 64-bit
> 
>  *** Using: /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz
> Traceback (most recent call last):
>   File "/usr/local/bin/rpi-source", line 383, in <module>
>     kernel = debian_method(debianlog)
>   File "/usr/local/bin/rpi-source", line 278, in debian_method
>     fw_rev = re.search(r'firmware as of ([0-9a-fA-F]+)', debian_changelog)
>   File "/usr/lib/python3.9/re.py", line 201, in search
>     return _compile(pattern, flags).search(string)
> TypeError: cannot use a string pattern on a bytes-like object
> ```
> 
> The error disappears when changing line 275 to:
> 
> ` debian_changelog = f.read().decode('utf-8')`

Done!

2022-08-31 07:27 UTC, lurch commented on rpi-source
> +        print(("\n *** %s" % str))
I'm fairly sure the extra brackets you've added here and on line 87 aren't necessary?

2022-08-31 07:29 UTC, lurch commented on rpi-source
> +    kernel.git_hash = download("%s/%s/git_hash" % (repo_raw, fw_rev)).strip().decode('UTF-8')
Should probably use 'utf-8' here rather than 'UTF-8', for consistency with the other `decode` functions in this script?

2023-09-01 10:00 UTC, pelwell commented
Fixed by #17.

2023-09-01 10:00 UTC, closed without merging